import "./globals.css";

// Commented out due to network restrictions in build environment
// import { Noto_Sans } from "next/font/google";
// const notoSans = Noto_Sans({
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

export const metadata = {
  title: "Louis Deng",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>

      <body>
        {children}
      </body>
    </html>
  );
}
